// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://khizcgryvscakouefofc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoaXpjZ3J5dnNjYWtvdWVmb2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzOTE3MDcsImV4cCI6MjA4ODk2NzcwN30.CkiSKYrfkKxi4WOXopqVMLSNV4HroqN_2kQgRogjj40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);